### ISSUE TITLE
Cannot map to database table without a primary key.

### ISSUE THREAD

**Issue by hur1can3** [jeffknupp/sandman#31] opened 2013-12-27 19:50 UTC
I get this error when trying to map to a ms sql server table without any primary keys.
sqlalchemy.exc.ArgumentError: Mapper Mapper could not assemble any primary key columns for mapped table

Full Trace
Traceback (most recent call last):
  File "c:/Python27/Scripts/sandmanctl", line 52, in <module>
    sys.exit(main())
  File "c:/Python27/Scripts/sandmanctl", line 48, in main
    activate(admin=True)
  File "C:\Python27\lib\site-packages\sandman\model__init__.py", line 78, in activate
    {'**tablename**': name})
  File "C:\Python27\lib\site-packages\flask_sqlalchemy__init__.py", line 510, in **init**
    DeclarativeMeta.**init**(self, name, bases, d)
  File "C:\Python27\lib\site-packages\sqlalchemy\ext\declarative\api.py", line 50, in **init**
    _as_declarative(cls, classname, cls.__dict__)
  File "C:\Python27\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 292, in _as_declarative
    mt.map()
  File "C:\Python27\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 376, in map
    **mapper_args
  File "C:\Python27\lib\site-packages\sqlalchemy\orm__init__.py", line 1229, in mapper
    return Mapper(class_, local_table, _args, *_params)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\mapper.py", line 221, in **init**
    self._configure_pks()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\mapper.py", line 824, in _configure_pks
    (self, self.mapped_table.description))
sqlalchemy.exc.ArgumentError: Mapper Mapper|Group_Subgroup_Contact|Group_Subgroup_Contact could not assemble any primary key columns for mapped table 'Group_Subgroup_Contact'

It would be nice to have a way to specify what column should map as primary key or allow none.

**Comment by jeffknupp** [comment] 2013-12-28 00:59
This is a duplicate of #27, but I think this ticket is more descriptive. Closing #27 in favor of this ticket.

**Comment by dmoco** [comment] 2013-12-30 06:42
I have a sqlite db with a table that has no primary key, just two text cols. If I use coded solution from issue #27 and flag the first col as the primary key then that column is not displayed (I get the same error as above if I don't do this).

**Comment by jeffknupp** [comment] 2013-12-30 16:02
@dmoco Actually, not displaying PK columns is a Flask-Admin default configuration setting. I'll make a change to add a flag allowing for showing PK columns.

**Comment by dmoco** [comment] 2014-01-01 09:16
Thanks Jeff!

**Closed as completed** 2014-01-03 05:10 UTC

**Comment by jeffknupp** [comment] 2014-01-03 05:12
You can should now be able to use `sandmanctl --primary-keys --all-columns-primary` to get around your issue. Sandman now creates primary keys for you if your database doesn't have them (by considering the union of all columns as the primary key). The only time this wouldn't work is if your database is so denormalized that it has duplicate table rows.

**Comment by dmoco** [comment] 2014-01-03 10:09
Installed latest version, tried a number of combinations and renaming tables but still get this error:

```
$ sandmanctl --primary-keys --all-columns-primary sqlite://///home/doc/std/dev/python/web/rest/sandman/test.sqlite
/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/clsregistry.py:159: SAWarning: This declarative base already contains a class with the same class name and module name as flask_sqlalchemy.xindexes, and will be replaced in the string-lookup table.
  existing.add_item(cls)
sandmanctl
Traceback (most recent call last):
  File "/usr/local/bin/sandmanctl", line 9, in <module>
    load_entry_point('sandman==0.7.0', 'console_scripts', 'sandmanctl')()
  File "/usr/local/lib/python2.7/dist-packages/sandman/sandmanctl.py", line 58, in main
    activate(name='sandmanctl')
  File "/usr/local/lib/python2.7/dist-packages/sandman/model/utils.py", line 155, in activate
    name)
  File "/usr/local/lib/python2.7/dist-packages/sandman/model/utils.py", line 130, in register_classes_for_admin
    admin_view.add_view(admin_view_class(cls, db_session))
  File "/usr/local/lib/python2.7/dist-packages/flask_admin/base.py", line 495, in add_view
    self.app.register_blueprint(view.create_blueprint(self))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 885, in register_blueprint
    (blueprint, self.blueprints[blueprint.name], blueprint.name)
AssertionError: A blueprint's name collision occurred between <flask.blueprints.Blueprint object at 0xa15f68c> and <flask.blueprints.Blueprint object at 0xa15946c>.  Both share the same name "xindexesview".  Blueprints that are created on the fly need unique names.
```

**Comment by jeffknupp** [comment] 2014-01-03 19:58
Sorry about that. See if version 0.7.1 fixes this (it should).

**Comment by dmoco** [comment] 2014-01-07 23:25
0.7.3 working great, thanks!

**Comment by dmoco** [comment] 2014-01-10 06:29
0.7.3 worked fine even without "--primary-keys --all-columns-primary". 0.7.5 fails again even with it...

```
 $ sandmanctl sqlite://///home/doc/std/dev/python/web/rest/sandman/test.sqlite
Traceback (most recent call last):
  File "/usr/local/bin/sandmanctl", line 9, in <module>
    load_entry_point('sandman==0.7.5', 'console_scripts', 'sandmanctl')()
  File "/usr/local/lib/python2.7/dist-packages/sandman/sandmanctl.py", line 63, in main
    activate(name='sandmanctl')
  File "/usr/local/lib/python2.7/dist-packages/sandman/model/utils.py", line 153, in activate
    generate_endpoint_classes(db, generate_pks)
  File "/usr/local/lib/python2.7/dist-packages/sandman/model/utils.py", line 28, in generate_endpoint_classes
    {'__tablename__': name})
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 510, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/api.py", line 53, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 321, in _as_declarative
    mt.map()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 404, in map
    **mapper_args
  File "<string>", line 2, in mapper
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 599, in __init__
    self._configure_pks()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1189, in _configure_pks
    (self, self.mapped_table.description))
sqlalchemy.exc.ArgumentError: Mapper Mapper|unlisted|unlisted could not assemble any primary key columns for mapped table 'unlisted'
```

```
$ sandmanctl --primary-keys --all-columns-primary sqlite://///home/doc/std/dev/python/web/rest/sandman/test.sqlite
Usage:
    sandmanctl.py URI [--show-pks --generate-pks] [--host=host] [--port=port]
```

**Comment by ryneeverett** [comment] 2014-01-11 03:17
Experiencing the same issue as @dmoco with 0.7.5.

**Comment by ryneeverett** [comment] 2014-01-11 20:06
In case you didn't figure it out already @dmoco, it looks like the `--primary-keys` and `--all-columns-primary` flags were deprecated a couple days ago when the entire `sandmanctl` syntax was overhauled. The syntax following `Usage:` seems to be correct, except for the `.py`.

**Comment by kxxoling** [comment] 2015-10-26 03:12
Same error occured with version 0.9.8
