### ISSUE TITLE
Error trying to access Skype DB

### ISSUE THREAD

**Issue by ghost** [jeffknupp/sandman#27] opened 2013-12-25 23:59 UTC
Trying to open Skype main.db:

```
Traceback (most recent call last):
  File "/Users/jan/.virtualenvs/sandman/bin/sandmanctl", line 52, in <module>
    sys.exit(main())
  File "/Users/jan/.virtualenvs/sandman/bin/sandmanctl", line 48, in main
    activate(admin=True)
  File "/Users/jan/.virtualenvs/sandman/lib/python2.7/site-packages/sandman/model/__init__.py", line 78, in activate
    {'__tablename__': name})
  File "/Users/jan/.virtualenvs/sandman/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 510, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "/Users/jan/.virtualenvs/sandman/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 50, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/Users/jan/.virtualenvs/sandman/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 292, in _as_declarative
    mt.map()
  File "/Users/jan/.virtualenvs/sandman/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 376, in map
    **mapper_args
  File "/Users/jan/.virtualenvs/sandman/lib/python2.7/site-packages/sqlalchemy/orm/__init__.py", line 1229, in mapper
    return Mapper(class_, local_table, *args, **params)
  File "/Users/jan/.virtualenvs/sandman/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 221, in __init__
    self._configure_pks()
  File "/Users/jan/.virtualenvs/sandman/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 824, in _configure_pks
    (self, self.mapped_table.description))
sqlalchemy.exc.ArgumentError: Mapper Mapper|AppSchemaVersion|AppSchemaVersion could not assemble any primary key columns for mapped table 'AppSchemaVersion'
```

**Comment by ghost** [comment] 2013-12-26 00:00
Same thing happened with Chrome's "History" DB:

```
sqlalchemy.exc.ArgumentError: Mapper Mapper|keyword_search_terms|keyword_search_terms could not assemble any primary key columns for mapped table 'keyword_search_terms'
```

**Comment by ghost** [comment] 2013-12-26 00:07
I realize that accessing this kind of application DB probably isn't what sandman is being built for primarily but it would be really awesome to have an instant local REST API for things like my browser history or past Skype messages, stuff like that..

**Comment by ghost** [comment] 2013-12-26 00:08
Not sure though if this is even fixable by sandman itself without significantly enhancing the sqlalchemy reflect feature

**Comment by jeffknupp** [comment] 2013-12-26 04:37
You should be able to do this if you give a little more info to sandman. Rather than just using sandmanctl, you could cook up a quick script and give sandman a little more info to go on via creating a few Models based on tables in the database. That said, it usually does work even with small databases like the one your testing (I've used it with my Chrome data before).

I'll take a look.

**Comment by jeffknupp** [comment] 2013-12-26 05:07
FYI, the following worked for Chrome's "History" file, although you would need to add a class for each table you want.

``` python
from sandman import app, db
from sandman.model import activate, Model, register
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////Users/jknupp/Library/Application Support/Google/Chrome/Default/History.bak'

class KeywordSearchTerm(Model):
    __tablename__ = 'keyword_search_terms'
    keyword_id = db.Column(db.Integer, primary_key=True)

register((KeywordSearchTerm))
activate(admin=True)
app.run(debug=True)
```

I'm going to do two things:
1. Add an option to explicitly specify a single class AND introspect the rest (which would be useful here, instead of having to specify all or none)
2. Add an option to "guess" at primary keys (likely just choosing the first column that works)

Either of these would fix your issue, but like I said, you can get around it today by writing a simple script.

**Comment by ghost** [comment] 2013-12-26 11:04
The guess option sounds perfect, especially if it's directly exposed through sandmanctl.

**Comment by jeffknupp** [comment] 2013-12-28 00:59
Dupe of #31.

**Closed as completed by jeffknupp** 2013-12-28 00:59 UTC
Labels: duplicate
