### ISSUE TITLE
Error using sandman on OpenERP 7 postgresql database

### ISSUE THREAD

**Issue by progressdll** [jeffknupp/sandman#29] opened 2013-12-27 09:18 UTC
trying to use sandman on a OpenERP 7 postgresql database
I get following output

/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/reflection.py:49: SAWarning: Skipped unsupported reflection of expression-based index res_currency_unique_name_company_id_idx
  ret = fn(self, con, _args, *_kw)
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/reflection.py:49: SAWarning: Skipped unsupported reflection of expression-based index ir_filters_name_model_uid_unique_index
  ret = fn(self, con, _args, *_kw)
Traceback (most recent call last):
  File "/usr/local/bin/sandmanctl", line 52, in <module>
    sys.exit(main())
  File "/usr/local/bin/sandmanctl", line 48, in main
    activate(admin=True)
  File "/usr/local/lib/python2.7/dist-packages/sandman/model/**init**.py", line 78, in activate
    {'**tablename**': name})
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/**init**.py", line 510, in **init**
    DeclarativeMeta.**init**(self, name, bases, d)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/api.py", line 50, in **init**
    _as_declarative(cls, classname, cls.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 292, in _as_declarative
    mt.map()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 376, in map
    **mapper_args
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/__init__.py", line 1229, in mapper
    return Mapper(class_, local_table, _args, *_params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 221, in **init**
    self._configure_pks()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 824, in _configure_pks
    (self, self.mapped_table.description))
sqlalchemy.exc.ArgumentError: Mapper Mapper|account_bank_statement_line_move_rel|account_bank_statement_line_move_rel could not assemble any primary key columns for mapped table 'account_bank_statement_line_move_rel'

**Comment by ghost** [comment] 2013-12-27 10:34
Same problem as #27

**Comment by jeffknupp** [comment] 2014-01-03 05:12
Closed as duplicate of #31

**Closed as completed by jeffknupp** 2014-01-03 05:12 UTC
Labels: duplicate
